import { describe, it, expect } from 'vitest';
import { renderSnapshot } from '../scripts/render-snapshot.js';
import type { State } from '../src/state.js';

const baseState: State = {
  schemaVersion: 1,
  currentRound: 2,
  currentPhase: 'implement',
  rounds: {
    '2': {
      captures: [
        { label: 'Login', path: '/login', filename: '01-login.png' },
        { label: 'Dashboard', path: '/dashboard', filename: '02-dashboard.png' },
      ],
      pushManifest: {
        pageId: '12:33',
        frames: [
          { label: 'Login', frameId: '12:34', imageHash: 'abc' },
          { label: 'Dashboard', frameId: '12:56', imageHash: 'def' },
        ],
      },
      comments: [
        {
          id: '12',
          frameLabel: 'Login',
          authorName: 'Sarah Lee',
          authorHandle: '@sarah',
          message: 'CTA hard to find.',
          createdAt: '2026-05-14T10:11:00Z',
          resolved: false,
        },
        {
          id: '17',
          frameLabel: 'Login',
          authorName: 'Mike Chen',
          authorHandle: '@mike',
          message: 'Form copy unclear.',
          createdAt: '2026-05-14T10:30:00Z',
          resolved: false,
        },
      ],
      themes: [
        {
          name: 'Navigation clarity',
          commentIds: ['12', '17'],
          summary: 'Users struggled to orient inside the app.',
        },
      ],
      plan: [
        {
          id: 'p1',
          themeName: 'Navigation clarity',
          change: 'Add breadcrumbs to Dashboard',
          drivesFrom: ['12', '17'],
          status: 'shipped',
        },
        {
          id: 'p2',
          themeName: 'Navigation clarity',
          change: 'Highlight active nav item',
          drivesFrom: ['12'],
          status: 'approved',
        },
      ],
    },
  },
};

describe('renderSnapshot', () => {
  it('starts with the generated-file warning header', () => {
    const md = renderSnapshot(baseState, 2);
    expect(md.startsWith('> Generated by figloops')).toBe(true);
    expect(md).toContain('Source of truth: feedback/state.json');
  });

  it('renders captures with frame IDs', () => {
    const md = renderSnapshot(baseState, 2);
    expect(md).toContain('01-login.png');
    expect(md).toContain('frameId: 12:34');
  });

  it('cites every comment by author name first, ID in parens', () => {
    const md = renderSnapshot(baseState, 2);
    expect(md).toContain('Sarah Lee (#12)');
    expect(md).toContain('Mike Chen (#17)');
  });

  it('renders themes as a markdown table with Theme / # / Cites / Summary columns', () => {
    const md = renderSnapshot(baseState, 2);
    expect(md).toContain('| Theme | # | Cites | Summary |');
    expect(md).toContain('|---|---|---|---|');
    expect(md).toMatch(/\| Navigation clarity \| 2 \| Sarah Lee, Mike Chen \| Users struggled to orient inside the app\. \|/);
  });

  it('collapses repeat authors in cite tally as "Name ×N"', () => {
    const stateRepeats: State = {
      ...baseState,
      rounds: {
        '2': {
          ...baseState.rounds['2'],
          themes: [
            {
              name: 'Form clarity',
              commentIds: ['12', '12', '17'], // Sarah twice, Mike once
              summary: 'Form-related friction.',
            },
          ],
        },
      },
    };
    const md = renderSnapshot(stateRepeats, 2);
    expect(md).toMatch(/\| Form clarity \| 3 \| Sarah Lee ×2, Mike Chen \|/);
  });

  it('escapes pipes and newlines in theme cells', () => {
    const stateWithMessyTheme: State = {
      ...baseState,
      rounds: {
        '2': {
          ...baseState.rounds['2'],
          themes: [
            {
              name: 'A | B',
              commentIds: ['12'],
              summary: 'line 1\nline 2',
            },
          ],
        },
      },
    };
    const md = renderSnapshot(stateWithMessyTheme, 2);
    expect(md).toContain('| A \\| B |');
    expect(md).toContain('line 1 line 2');
    expect(md).not.toContain('line 1\nline 2');
  });

  it('renders plan items with shipped/pending checkboxes', () => {
    const md = renderSnapshot(baseState, 2);
    expect(md).toContain('[✓] Add breadcrumbs to Dashboard');
    expect(md).toContain('[ ] Highlight active nav item');
  });

  it('cites plan items with author names in Drives from', () => {
    const md = renderSnapshot(baseState, 2);
    expect(md).toMatch(/Drives from: .*Sarah Lee \(#12\).*Mike Chen \(#17\)/);
  });

  it('throws if the requested round is not in state', () => {
    expect(() => renderSnapshot(baseState, 99)).toThrow(/round 99/);
  });

  it('renders an empty round gracefully (no captures yet)', () => {
    const empty: State = {
      ...baseState,
      currentRound: 1,
      currentPhase: 'capture',
      rounds: {
        '1': { captures: [], pushManifest: null, comments: [], themes: [], plan: [] },
      },
    };
    const md = renderSnapshot(empty, 1);
    expect(md).toContain('Round 1');
    expect(md).toContain('_no captures yet_');
  });
});
