// Regenerates feedback/round-N/snapshot.md from feedback/state.json.
// The snapshot is a read-only audit artifact; figloops never reads it back.
//
// CLI usage: tsx scripts/render-snapshot.ts <round?>
// If <round> is omitted, uses state.currentRound.
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { loadState, type State, type Comment, type PlanItem, type RoundData } from '../src/state.js';

function cite(c: Comment): string {
  return `${c.authorName} (#${c.id})`;
}

function citeMany(comments: Comment[], ids: string[]): string {
  const byId = new Map(comments.map((c) => [c.id, c]));
  return ids
    .map((id) => {
      const c = byId.get(id);
      return c ? cite(c) : `#${id}`;
    })
    .join(', ');
}

function renderCaptures(round: RoundData): string {
  if (round.captures.length === 0) {
    return '_no captures yet_';
  }
  const byLabel = new Map(round.pushManifest?.frames.map((f) => [f.label, f.frameId]) ?? []);
  return round.captures
    .map((c) => {
      const frameId = byLabel.get(c.label);
      const frameSuffix = frameId ? ` (frameId: ${frameId})` : '';
      return `- ${c.filename}      → frame "${c.label}"${frameSuffix}`;
    })
    .join('\n');
}

function renderComments(round: RoundData): string {
  if (round.comments.length === 0) {
    return '_no comments yet_';
  }
  const lines: string[] = [];
  for (const c of round.comments) {
    const dateOnly = c.createdAt.slice(0, 10);
    const frame = c.frameLabel ? `"${c.frameLabel}"` : '(no frame)';
    lines.push(`- #${c.id} ${c.authorName} on ${frame} (${dateOnly})`);
    lines.push(`  "${c.message}"`);
  }
  return lines.join('\n');
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function renderThemes(round: RoundData): string {
  if (round.themes.length === 0) {
    return '_no themes yet_';
  }
  const lines: string[] = ['| Theme | Cites | Summary |', '|---|---|---|'];
  for (const t of round.themes) {
    const name = escapeCell(t.name);
    const cites = escapeCell(citeMany(round.comments, t.commentIds));
    const summary = escapeCell(t.summary);
    lines.push(`| ${name} | ${cites} | ${summary} |`);
  }
  return lines.join('\n');
}

function renderPlan(round: RoundData): string {
  if (round.plan.length === 0) {
    return '_no plan yet_';
  }
  const byTheme = new Map<string, PlanItem[]>();
  for (const item of round.plan) {
    const list = byTheme.get(item.themeName) ?? [];
    list.push(item);
    byTheme.set(item.themeName, list);
  }
  const lines: string[] = [];
  for (const [themeName, items] of byTheme) {
    lines.push(`### ${themeName}`);
    for (const item of items) {
      const check = item.status === 'shipped' ? '[✓]' : '[ ]';
      lines.push(`- ${check} ${item.change}`);
      lines.push(`      Drives from: ${citeMany(round.comments, item.drivesFrom)}`);
    }
    lines.push('');
  }
  return lines.join('\n').trimEnd();
}

function planSummary(round: RoundData): string {
  const total = round.plan.length;
  if (total === 0) return '';
  const approved = round.plan.filter((p) => p.status === 'approved' || p.status === 'shipped').length;
  const shipped = round.plan.filter((p) => p.status === 'shipped').length;
  return ` (${approved} approved · ${shipped} shipped · ${approved - shipped} pending)`;
}

export function renderSnapshot(state: State, round: number): string {
  const data = state.rounds[String(round)];
  if (!data) {
    throw new Error(`renderSnapshot: state has no entry for round ${round}`);
  }
  const phaseLabel = state.currentRound === round ? state.currentPhase : 'closed';
  return [
    '> Generated by figloops. Edits will be overwritten on the next /figloops:next.',
    '> Source of truth: feedback/state.json',
    '',
    `# Round ${round} · Phase: ${phaseLabel}`,
    '',
    '## Captures',
    renderCaptures(data),
    '',
    `## Comments (${data.comments.length})`,
    renderComments(data),
    '',
    '## Themes',
    renderThemes(data),
    '',
    `## Plan${planSummary(data)}`,
    renderPlan(data),
    '',
  ].join('\n');
}

// CLI entry point
async function main() {
  const cwd = process.cwd();
  const statePath = join(cwd, 'feedback', 'state.json');
  const state = loadState(statePath);
  const round = process.argv[2] ? Number(process.argv[2]) : state.currentRound;
  const md = renderSnapshot(state, round);
  const outDir = join(cwd, 'feedback', `round-${round}`);
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, 'snapshot.md');
  writeFileSync(outPath, md);
  process.stdout.write(JSON.stringify({ round, wroteTo: outPath }, null, 2));
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  main().catch((err) => {
    process.stderr.write(`[render-snapshot] fatal: ${err.message}\n`);
    process.exit(1);
  });
}
